// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcznpwzcmljoechzfemi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impjem5wd3pjbWxqb2VjaHpmZW1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1MzM0NjcsImV4cCI6MjA1NTEwOTQ2N30.8JL7sCOeS0V-ySXj5qN5EHZ1gHCKUj3f4j1K2NugZcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);